### ISSUE TITLE
Resarch User Profile and Data Storage and Management

### ISSUE THREAD

**Issue by nickheady** [Ryan-Korteway/GVSSS#4]

**Comment by nickheady** [comment]
Where is user profile information going to be stored?
How will all data related to trips be stored and tracked?

**Comment by Ryan-Korteway** [comment]
Firebase handles both data storage and user sign in/up and authentication through several different providers as well as just letting us collect email addresses and passwords to use for user accounts. 

Currently only my plan for trip data is keeping a persistent list on the phone of everyone the user has paid and therefore ridden with.

**Comment by chrismic** [comment]
I agree with Ryan that Firebase seems like a great option for storing profile information and signing in/up.  I think we should also shoot for keeping data on all the trips so we can have some stats once we release the app.

**Comment by Ryan-Korteway** [comment]
Okay so I did a quick bit of research just now to see how to do sign in through firebase email and password sets up etc and it looks very easy to do at least in code, and it gives us the control we need to say "hey, mail.gvsu.edu emails only". Setting up the UI might be another matter but thats just a bunch of labels and text boxes as well as applying some rules on how secure to make the passwords

**Comment by nickheady** [comment]
Was able to read and write from Firebase using public security settings. Next step is to look into account creation, and restricting users to be able to access ONLY their data.

**Comment by Ryan-Korteway** [comment]
Account creation other than the segways to the account creation page for the first time log ins/sign ups should be understood by me already.

I am currently testing if my prevention/protection idea is going to work.

As for only the user getting their own info down from the database, we could use the function
queryEqualToValue() and the value argument to the function would be the same email address the apps user signed in with or better yet, the UUID of the user that gets created at sign up time, if we can access it and throw it into the profiles section of the database,

My concerns at this time is finding how to update  existing entries, instead of just always making new ones, so there are not three different accounts for driver jim, each with a different rate, with only one of them being the rate he really wants to charge people for.

**Comment by Ryan-Korteway** [comment]
Okay so my if(email.hasSuffix(mail.gvsu.edu)) { sign in code } solution does work and nothing seems to happen if you try to put your real email address in and tag the mail.gvsu.edu part onto the end of the email address box.

**Comment by Ryan-Korteway** [comment]
it is not letting me make a new account with the same email address when i hit create Account which is a nice thing to know.
