### ISSUE TITLE
Research Security

### ISSUE THREAD

**Issue by nickheady** [Ryan-Korteway/GVSSS#7]
How will we restrict users to having a GVSU .edu email account?
How much user information will we require? Phone, address, etc?
If we integrate Paypal, Apple Pay, etc. do they handle security?

**Comment by Ryan-Korteway** [comment]
In my mind the only info we need is the gvsu email, name, and phone number, on top of their rate if they are a driver, and of course location information for the app's map when the time comes.

We make it so that you cannot sign up/into the app unless the text/email address entered into the "Sign in/Sign up" text area/box in the ui ends in "mail.gvsu.edu"

As for the braintree backend and how they handle security, that i do not know.

I also still need to see how secure signing into firebase through the app will be, if the example code given out in the developer docks is the "secure code" or if something else is required.
